## PyTorch Tensors & NumPy
Numpy is a popular scientific Python numerical computing library
and because of this, PyTorch has functionality to interact with it.

* Data in NumPy array, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor, want in NumPy -> `torch.Tensor.numpy()`

In [ ]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype float64 unless specified otherwise
print(array)
print(tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [4]:
print(tensor.dtype)
print(torch.arange(1.0, 8.0).dtype)

torch.float64
torch.float32


In [5]:
# change the value of array, what will this do to tensor?
array = array + 1
print(array)
print(tensor)

[2. 3. 4. 5. 6. 7. 8.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [7]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor)
print(numpy_tensor)
print(numpy_tensor.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]
float32
