# Deep Learning with PyTorch Course
## Course GitHub - https://github.com/mrdbourke/pytorch-deep-learning/


## 00.Pytorch_fundamentals - https://youtu.be/V_xro1bcAuA?si=-SdptFgjTdf6gtrw 1:14:28
### Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [66]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1


### Introduction to Tensors

In [67]:
# scalar
scalar = torch.tensor(7)
print(scalar)

no_of_dimensions = scalar.ndim
print(no_of_dimensions)

# get the tensor back as a Python list
print(scalar.item())

# Vector
vector = torch.tensor([7,7])
print(vector)



tensor(7)
0
7
tensor([7, 7])


In [68]:
# Matrix 
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])

print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [69]:
# understanding dimensions of tensors in PyTorch
tensor = torch.tensor([[[8,10,12],
                        [9,11,13],
                        [10,12,14]]])
print(tensor.ndim)
print(tensor.shape)

print(tensor[0])
print(tensor[0,0])
print(tensor[0,1,2])

# In this cell, we create a 3D tensor with shape (1, 3, 3).
# The tensor has 3 dimensions, so tensor.ndim returns 3.
# Dimensions in a tensor are counted by how many index positions
# are needed to access an element: the first dimension selects
# the 2D matrix, the second selects the row, and the third selects
# the element within that row.
#
# tensor.shape shows the size of each dimension: here (1, 3, 3)
# means 1 matrix, 3 rows, and 3 columns. Using tensor[0],
# tensor[0,1], and tensor[0,1,2] demonstrates how indexing works
# across these dimensions.

3
torch.Size([1, 3, 3])
tensor([[ 8, 10, 12],
        [ 9, 11, 13],
        [10, 12, 14]])
tensor([ 8, 10, 12])
tensor(13)


### Why create random tensors? 
Random tensors are important because many neural networks first start learning by initializing tensors filled with random numbers and adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

In [70]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[[0.1957, 0.4397, 0.8991, 0.1600],
         [0.6348, 0.5176, 0.9140, 0.5984],
         [0.5953, 0.1316, 0.9622, 0.5668]]])
3


In [71]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour, channel
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


### Zeros and Ones

In [72]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
print(zeros)

# Create a tensor of all ones

ones = torch.ones(size=(3,4))
print(ones)

print(zeros.dtype, ones.dtype) # dtype is a keyword that returns the data types of a particular tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32 torch.float32


### Creating a range of tensors and tensors-like

In [73]:
# Use torch.arange()
zero_to_9 = torch.arange(0, 10)
print(zero_to_9)
zero_to_9 = torch.arange(0, 10, step=2)
print(zero_to_9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [74]:
# Creating tensors like
one_to_10 = torch.arange(1,11,step=1)
ten_zeros = torch.zeros_like(input=one_to_10)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Data types
**Note:** Tensor data types is one of the 3 big errors with PyTorch and Deep Learning
1. Tensors not right data type
2. Tensors not right shape
3. Tensors not on the right device

In [75]:
# Float32 Tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, 
                               device=None, requires_grad=False)
print(float_32_tensor)

# Converting a variable from one data type to another data type
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.])
tensor([3., 6., 9.], dtype=torch.float16)


### Getting information from tensors - `Tensor Attributes`
1. Tensors not right data type - use `tensors.dtype` to get the datatype of tensors
2. Tensors not right shape - use `tensors.shape` to get the shape of tensors
3. Tensors not on the right device - `tensors.device` to get the device on which these tensors are

In [76]:
some_tensor =   torch.rand(3, 4)
print(some_tensor)

tensor([[0.1554, 0.7641, 0.2022, 0.9234],
        [0.2700, 0.1334, 0.5052, 0.7320],
        [0.4588, 0.2064, 0.6900, 0.2289]])


In [77]:
# get details about the tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.1554, 0.7641, 0.2022, 0.9234],
        [0.2700, 0.1334, 0.5052, 0.7320],
        [0.4588, 0.2064, 0.6900, 0.2289]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


In [78]:
# Changing the device that the tensor is on
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

gpu_some_tensor = some_tensor.to(device)
print(f"Device of the tensor: {gpu_some_tensor.device}")

Device of the tensor: cuda:0


### Manipulating Tensors (Tensor Operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [79]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
print(tensor)
# Addition
print(tensor+10)

tensor([1, 2, 3])
tensor([11, 12, 13])


In [80]:
# Subtraction
print(tensor-10)


tensor([-9, -8, -7])


In [81]:
# Multiplication
print(tensor*10)


tensor([10, 20, 30])


In [82]:
# Division
print(tensor/10)

tensor([0.1000, 0.2000, 0.3000])


In [83]:
# Try out pytorch in-built functions
print(torch.add(tensor, 10))
print(torch.subtract(tensor, 10))
print(torch.multiply(tensor, 10))
print(torch.divide(tensor, 10))


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


#### Matrix multiplication
Two main ways of performing multiplication in a neural network
1. Element-Wise multiplication
2. Matrix multiplication

There are two main rules to satisfy before doing matrix multiplication:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`

In [ ]:
# Matrix multiplication
print(torch.matmul(tensor, tensor)) # this method makes matrix multiplication faster as compared to manual matrix multiplication
# this code is less verbose and faster
# matmul gives dot product of matrices

tensor(14)