# Deep Learning with PyTorch Course
## Course GitHub - https://github.com/mrdbourke/pytorch-deep-learning/


## 00.Pytorch_fundamentals - https://youtu.be/V_xro1bcAuA?si=-SdptFgjTdf6gtrw 1:14:28
### Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1


### Introduction to Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar)

no_of_dimensions = scalar.ndim
print(no_of_dimensions)

# get the tensor back as a Python list
print(scalar.item())

# Vector
vector = torch.tensor([7,7])
print(vector)



tensor(7)
0
7
tensor([7, 7])


TypeError: tensor() missing 1 required positional arguments: "data"

In [ ]:
# Matrix 
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])

print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [ ]:
# understanding dimensions of tensors in PyTorch
tensor = torch.tensor([[[8,10,12],
                        [9,11,13],
                        [10,12,14]]])
print(tensor.ndim)
print(tensor.shape)

print(tensor[0])
print(tensor[0,0])
print(tensor[0,1,2])

# In this cell, we create a 3D tensor with shape (1, 3, 3).
# The tensor has 3 dimensions, so tensor.ndim returns 3.
# Dimensions in a tensor are counted by how many index positions
# are needed to access an element: the first dimension selects
# the 2D matrix, the second selects the row, and the third selects
# the element within that row.
#
# tensor.shape shows the size of each dimension: here (1, 3, 3)
# means 1 matrix, 3 rows, and 3 columns. Using tensor[0],
# tensor[0,1], and tensor[0,1,2] demonstrates how indexing works
# across these dimensions.

3
torch.Size([1, 3, 3])
tensor([[ 8, 10, 12],
        [ 9, 11, 13],
        [10, 12, 14]])
tensor([ 8, 10, 12])
tensor(13)


### Why create random tensors? 
Random tensors are important because many neural networks first start learning by initializing tensors filled with random numbers and adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[[[0.0780, 0.8211, 0.9171, 0.6729],
          [0.1381, 0.9076, 0.4334, 0.7893],
          [0.8203, 0.3393, 0.1298, 0.1308]]]])
4


In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = 