# Deep Learning with PyTorch Course
## Course GitHub - https://github.com/mrdbourke/pytorch-deep-learning/


## 00.Pytorch_fundamentals - https://youtu.be/V_xro1bcAuA?si=-SdptFgjTdf6gtrw 1:14:28
### Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [40]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1


### Introduction to Tensors

In [41]:
# scalar
scalar = torch.tensor(7)
print(scalar)

no_of_dimensions = scalar.ndim
print(no_of_dimensions)

# get the tensor back as a Python list
print(scalar.item())

# Vector
vector = torch.tensor([7,7])
print(vector)



tensor(7)
0
7
tensor([7, 7])


In [42]:
# Matrix 
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])

print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [43]:
# understanding dimensions of tensors in PyTorch
tensor = torch.tensor([[[8,10,12],
                        [9,11,13],
                        [10,12,14]]])
print(tensor.ndim)
print(tensor.shape)

print(tensor[0])
print(tensor[0,0])
print(tensor[0,1,2])

# In this cell, we create a 3D tensor with shape (1, 3, 3).
# The tensor has 3 dimensions, so tensor.ndim returns 3.
# Dimensions in a tensor are counted by how many index positions
# are needed to access an element: the first dimension selects
# the 2D matrix, the second selects the row, and the third selects
# the element within that row.
#
# tensor.shape shows the size of each dimension: here (1, 3, 3)
# means 1 matrix, 3 rows, and 3 columns. Using tensor[0],
# tensor[0,1], and tensor[0,1,2] demonstrates how indexing works
# across these dimensions.

3
torch.Size([1, 3, 3])
tensor([[ 8, 10, 12],
        [ 9, 11, 13],
        [10, 12, 14]])
tensor([ 8, 10, 12])
tensor(13)


### Why create random tensors? 
Random tensors are important because many neural networks first start learning by initializing tensors filled with random numbers and adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

In [44]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[[0.0217, 0.8447, 0.1510, 0.4692],
         [0.0075, 0.3836, 0.1925, 0.3861],
         [0.9877, 0.9076, 0.4752, 0.3747]]])
3


In [45]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour, channel
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


### Zeros and Ones

In [46]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
print(zeros)

# Create a tensor of all ones

ones = torch.ones(size=(3,4))
print(ones)

print(zeros.dtype, ones.dtype) # dtype is a keyword that returns the data types of a particular tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32 torch.float32


### Creating a range of tensors and tensors-like

In [47]:
# Use torch.arange()
zero_to_9 = torch.arange(0, 10)
print(zero_to_9)
zero_to_9 = torch.arange(0, 10, step=2)
print(zero_to_9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [48]:
# Creating tensors like
one_to_10 = torch.arange(1,11,step=1)
ten_zeros = torch.zeros_like(input=one_to_10)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Data types
**Note:** Tensor data types is one of the 3 big errors with PyTorch and Deep Learning
1. Tensors not right data type
2. Tensors not right shape
3. Tensors not on the right device

In [50]:
# Float32 Tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, 
                               device=None, requires_grad=False)
print(float_32_tensor)

tensor([3., 6., 9.])
